//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BubbleShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public System.TimeSpan EffectiveFrom { get; set; }
        public string Description { get; set; }
        public System.TimeSpan LastUpdated { get; set; }
        public int Product_Id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
