//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BubbleShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPaymentMethod
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Identifier { get; set; }
        public string Expiry { get; set; }
        public string Name { get; set; }
        public string BillingAddress { get; set; }
        public string CreatedOn { get; set; }
        public System.TimeSpan LastUpdated { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
